#ifndef OMNIDIRECTIONAL_DRIVER__VISIBILITY_CONTROL_H_
#define OMNIDIRECTIONAL_DRIVER__VISIBILITY_CONTROL_H_

#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define OMNIDIRECTIONAL_DRIVER_EXPORT __attribute__ ((dllexport))
    #define OMNIDIRECTIONAL_DRIVER_IMPORT __attribute__ ((dllimport))
  #else
    #define OMNIDIRECTIONAL_DRIVER_EXPORT __declspec(dllexport)
    #define OMNIDIRECTIONAL_DRIVER_IMPORT __declspec(dllimport)
  #endif
  #ifdef OMNIDIRECTIONAL_DRIVER_BUILDING_LIBRARY
    #define OMNIDIRECTIONAL_DRIVER_PUBLIC OMNIDIRECTIONAL_DRIVER_EXPORT
  #else
    #define OMNIDIRECTIONAL_DRIVER_PUBLIC OMNIDIRECTIONAL_DRIVER_IMPORT
  #endif
  #define OMNIDIRECTIONAL_DRIVER_PUBLIC_TYPE OMNIDIRECTIONAL_DRIVER_PUBLIC
  #define OMNIDIRECTIONAL_DRIVER_LOCAL
#else
  #define OMNIDIRECTIONAL_DRIVER_EXPORT __attribute__ ((visibility("default")))
  #define OMNIDIRECTIONAL_DRIVER_IMPORT
  #if __GNUC__ >= 4
    #define OMNIDIRECTIONAL_DRIVER_PUBLIC __attribute__ ((visibility("default")))
    #define OMNIDIRECTIONAL_DRIVER_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define OMNIDIRECTIONAL_DRIVER_PUBLIC
    #define OMNIDIRECTIONAL_DRIVER_LOCAL
  #endif
  #define OMNIDIRECTIONAL_DRIVER_PUBLIC_TYPE
#endif

#endif  // OMNIDIRECTIONAL_DRIVER__VISIBILITY_CONTROL_H_